version: "3"
services:
  engecopi_prdecomerce:
    image: tomcat:8
    container_name: eng_pedido_reserva
    ports:
      - "8019:8080"
    environment:
      TZ: "America/Fortaleza"
      EBEAN_PROPS: /etc/ebean.properties
      LANG: 'pt_BR.UTF-8'
      LANGUAGE: 'pt_BR:pt'
      LC_ALL: 'pt_BR.UTF-8'
    volumes:
      - ./build/libs/producao.war:/usr/local/tomcat/webapps/pedidoReserva.war
      - ./ebean.properties:/etc/ebean.properties
    restart: always
    networks:
      rede_pedido_reserva:
        ipv4_address: 172.119.1.1
networks:
  rede_pedido_reserva:
    ipam:
      driver: default
      config:
        - subnet: 172.119.0.0/16
